### PR TITLE
add yq

### PR DESCRIPTION
**Pull request by bryanwieg**
adds the yq (github.com/mikefarah/yq/) yaml processor

### CODE REVIEW

**Comment by bryanwieg** [comment]
I gave a shot at integrating it with renovate. please let me know if you prefer another approach

**Comment by budimanjojo** [comment]
Thanks for the PR! One thing about the renovate is it will update the image whenever the GH repository `mikefarah/qy` release a new version. Will the apk repository http://dl-cdn.alpinelinux.org/alpine/edge/community gets the updated version as soon as the git repo create a new release? If not then the renovate updating image might break.

**Comment by budimanjojo** [comment]
I see that `yq` release does include all the binary assets in all kind of formats, You can download the binary and put it inside `/usr/local/bin` like how I do `kustomize` etc. There's an extracted version https://github.com/mikefarah/yq/releases/download/v4.34.2/yq_linux_amd64 that you can just curl and rename it to `yq` without needing to use `tar` too.

**Comment by bryanwieg** [comment]
I see your point. Besides, if i understand correctly, it looks the alpine package maintainer appears to only publish the latest version of yq with each release of alpine, and is not publishing all released versions of yq itself.

https://pkgs.alpinelinux.org/packages?name=yq&branch=v3.18&repo=community&arch=&maintainer=

**Comment by budimanjojo** [comment]
Maybe do it like this might be better because we don't need to worry if the alpine repo is updated or not:
```
RUN curl -L -o /usr/local/bin/yq \
    https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 \
    && chmod +x /usr/local/bin/yq
```

**Comment by bryanwieg** [comment]
also, if it seems ok to you, how would you feel about adding `ca-certificates`, `openssh-client`, and `curl` (well, just don't del curl)?

it would allow the container to clone a remote git manifest repo, update a manifest yaml with yq, and commit the change.

i can add it in another commit or this one if preferred

**Comment by bryanwieg** [comment]
> Maybe do it like this might be better because we don't need to worry if the alpine repo is updated or not:
> 
> ```
> RUN curl -L -o /usr/local/bin/yq \
>     https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_amd64 \
>     && chmod +x /usr/local/bin/yq
> ```

I did try this, and i'm not sure whether it's an issue with how that package is built vs the one in the alpine repo... but i found that the one in the alpine repo did not encounter certain errors that the prebuilt binaries on github did- even given the same version of yq.

**Comment by budimanjojo** [comment]
> also, if it seems ok to you, how would you feel about adding `ca-certificates`, `openssh-client`, and `curl` (well, just don't del curl)?
> 
> it would allow the container to clone a remote git manifest repo, update a manifest yaml with yq, and commit the change.
> 
> i can add it in another commit or this one if preferred

I'm not sure about adding `openssh` and `ca-certificates`. I don't think pushing a commit from a linting tool output is a good practice imho. It should be the linting tool telling you about something is wrong and you fix it manually based on the suggestion given or  even chose to ignore it sometimes. But that's just my opinion. Are u sure having them in the container is a good choice?

**Comment by bryanwieg** [comment]
i understand, and I can separate it to another container. 

The way I had imagined it, just using different ci stages. One stage for linting, then another stage to update k8s manifests / deploy config to the environments. 

My goal or thought was to use the same image for all these stages- linting and k8s manifest updates, since all these operations share so much in common, and having just slightly different containers for each seemed unnecessary.

**Comment by budimanjojo** [comment]
Okay I'll let this slide because there's maybe only a couple of people using this container anyway. :smile:

**Comment by budimanjojo** [comment]
Fixes: https://github.com/budimanjojo/kubernetes-toolbox/issues/154

**Pull request merged**
